version: '3'
services:
    mongodb:
        restart: always
        build: ./mongo
        ports:
            - "27018:27017"
    rabbitmq:
        restart: always
        build: ./rabbitmq
        ports: 
            - "5672:5672"
    consumer:
        restart: always
        build: ./consumer
        links:
            - rabbitmq
            - mongodb
